//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveCommerce.Training.ShippingIntegration.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IShippingService")]
    public interface IShippingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/GetShippingCost", ReplyAction="http://tempuri.org/IShippingService/GetShippingCostResponse")]
        decimal GetShippingCost(decimal weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShippingService/GetShippingCost", ReplyAction="http://tempuri.org/IShippingService/GetShippingCostResponse")]
        System.Threading.Tasks.Task<decimal> GetShippingCostAsync(decimal weight);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShippingServiceChannel : ActiveCommerce.Training.ShippingIntegration.Services.IShippingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShippingServiceClient : System.ServiceModel.ClientBase<ActiveCommerce.Training.ShippingIntegration.Services.IShippingService>, ActiveCommerce.Training.ShippingIntegration.Services.IShippingService {
        
        public ShippingServiceClient() {
        }
        
        public ShippingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShippingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal GetShippingCost(decimal weight) {
            return base.Channel.GetShippingCost(weight);
        }
        
        public System.Threading.Tasks.Task<decimal> GetShippingCostAsync(decimal weight) {
            return base.Channel.GetShippingCostAsync(weight);
        }
    }
}
